"""C0 golden fixtures: regenerated bytes, MANIFEST pin and both validators agree."""

import hashlib
import json
from pathlib import Path

import pytest

import c1_envelopes as envs
from c1_contract import C1ContractError
from c1_receiver import ReferenceReceiver
import ext_contract as ext
import ext_fixtures

ROOT = ext_fixtures.ROOT
INDEX = json.loads((ROOT / "index.json").read_text(encoding="utf-8"))["fixtures"]
SPEC = Path(__file__).resolve().parents[2] / "docs" / "specs" / "external-export-contract.md"


def _cases(profile, expect=None):
    return [c for c in INDEX if c["profile"] == profile and c["path"]
            and (expect is None or c["expect"] == expect)]


def _oracle(value):
    """Independent canonical JSON for the fixture domain (6-digit fixed floats)."""
    if isinstance(value, bool) or value is None:
        return json.dumps(value)
    if isinstance(value, float):
        return str(int(value)) if value.is_integer() else (
            "%.6f" % value).rstrip("0").rstrip(".")
    if isinstance(value, int | str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ",".join(_oracle(v) for v in value) + "]"
    return "{" + ",".join(json.dumps(k, ensure_ascii=False) + ":" + _oracle(value[k])
                          for k in sorted(value)) + "}"


def _sha(value):
    return hashlib.sha256(_oracle(value).encode()).hexdigest()


def test_committed_bytes_equal_regenerated_and_manifest_pins_them():
    generated = ext_fixtures.generate()
    on_disk = {str(p.relative_to(ROOT)): p.read_bytes()
               for p in ROOT.rglob("*") if p.is_file()}
    assert on_disk == generated
    for line in generated["MANIFEST.sha256"].decode().splitlines():
        digest, path = line.split("  ", 1)
        assert hashlib.sha256(on_disk[path]).hexdigest() == digest
    assert set(generated) - {"MANIFEST.sha256"} == {
        line.split("  ", 1)[1] for line in generated["MANIFEST.sha256"].decode().splitlines()}


def test_fixture_set_id_is_recorded_in_the_contract_spec():
    assert ext_fixtures.fixture_set_id(ext_fixtures.generate()) in SPEC.read_text(encoding="utf-8")


def test_counts_match_the_c0_plan():
    assert len({c["path"].split("/")[1][:2] for c in _cases("c1", "accept")}) == 12
    assert len(_cases("c1", "reject")) == 23
    assert [c["id"] for c in INDEX if c.get("generated_only")] == ["rejected/15-envelope-too-large"]
    assert len(_cases("receipt")) == 6 and len(_cases("withdraw")) == 4


@pytest.mark.parametrize("case", _cases("c1", "accept"), ids=lambda c: c["path"])
def test_accepted_passes_producer_receiver_and_independent_hash(case, tmp_path):
    raw = (ROOT / case["path"]).read_bytes()
    envelope = envs.parse_envelope(raw)
    ext._validate_envelope(json.loads(raw))
    assert _oracle(envelope).encode() == raw
    assert envelope["records_sha256"] == _sha(envelope["records"])
    assert envelope["envelope_id"] == _sha({k: envelope.get(k) for k in (
        "contract", "auth_id", "snapshot_generation_id", "records_sha256", "part")})[:24]
    receiver = ReferenceReceiver(tmp_path / "r", source_label="c0")
    assert receiver.receive_wire(raw, now=ext_fixtures.FIXED_NOW) == envelope["envelope_id"]


def test_split_set_is_complete_and_bound(tmp_path):
    parts = [envs.parse_envelope((ROOT / c["path"]).read_bytes())
             for c in INDEX if c.get("set") == "05-split"]
    assert [p["part"]["index"] for p in parts] == [1, 2, 3]
    assert envs.validate_collection(parts)["status"] == "complete"
    assert parts[0]["part"]["set"] == _sha([p["records_sha256"] for p in parts])
    receiver = ReferenceReceiver(tmp_path / "r", source_label="c0")
    for part in parts:
        receiver.receive(part, now=ext_fixtures.FIXED_NOW)
    assert receiver.diagnostics(now=ext_fixtures.FIXED_NOW)["status"] == "ok"


@pytest.mark.parametrize("case", _cases("c1", "reject"), ids=lambda c: c["path"])
def test_rejected_gives_the_same_code_on_both_sides(case, tmp_path):
    raw = (ROOT / case["path"]).read_bytes()
    with pytest.raises(C1ContractError) as receiver_side:
        envs.parse_envelope(raw)
    with pytest.raises(ext.ContractError) as producer_side:
        ext._validate_envelope(json.loads(raw))
    with pytest.raises(C1ContractError) as reference:
        ReferenceReceiver(tmp_path / "r", source_label="c0").receive_wire(
            raw, now=ext_fixtures.FIXED_NOW)
    assert receiver_side.value.code == str(producer_side.value) == reference.value.code \
        == case["code"]


def test_generated_only_oversize_is_rejected_by_byte_cap():
    raw = ext_fixtures.envelope_too_large()
    assert len(raw) > envs.MAX_WIRE_BYTES
    with pytest.raises(C1ContractError) as e:
        envs.parse_envelope(raw)
    assert e.value.code == "envelope_too_large"


@pytest.mark.parametrize("case", _cases("withdraw"), ids=lambda c: c["path"])
def test_withdraw_directives(case):
    raw = (ROOT / case["path"]).read_bytes()
    if case["expect"] == "accept":
        assert envs.parse_withdrawal(raw)["reason"] == "operator_request"
        return
    with pytest.raises(C1ContractError) as e:
        envs.parse_withdrawal(raw)
    assert e.value.code == case["code"]


@pytest.mark.parametrize("case", _cases("receipt"), ids=lambda c: c["path"])
def test_receipts_parse_and_drive_the_sender_journal(case, tmp_path, monkeypatch):
    raw = (ROOT / case["path"]).read_bytes()
    if case["expect"] == "reject":
        with pytest.raises(ext.ContractError) as e:
            ext.parse_receipt(raw)
        assert str(e.value) == case["code"]
        return
    ext.parse_receipt(raw)
    monkeypatch.setattr(ext.time, "time", lambda: ext_fixtures.FIXED_NOW)
    auth = tmp_path / "auth.json"
    auth.write_text(json.dumps({
        "contract": ext.AUTH_CONTRACT, "auth_id": ext_fixtures.AUTH_ID,
        "purpose": ext_fixtures.PURPOSE, "actor": "synthetic-c0",
        "destination": ext_fixtures.DESTINATION, "scope": "aggregate", "patients": "all",
        "fields": ["meta", "coverage", "message", "message_body", "patient_coverage",
                   "signal", "signals_truncated"],
        "expires_at": ext_fixtures.FIXED_NOW + 3600, "max_snapshot_age_s": 3600,
        "retention_days": 30, "confirm_human": True, "reason": "synthetic c0"}))
    sink = ext.HandoffSink(tmp_path / "outbox")
    exporter = ext.GovernedExporter(tmp_path / "state")
    envelope = json.loads((ROOT / "accepted" / "01-basic.json").read_bytes())
    assert exporter.deliver(envelope, sink, auth_path=auth)["status"] == "held"
    if json.loads(raw)["kind"] == "delete":
        assert exporter.withdraw(envelope["envelope_id"], sink)["status"] == "delete_held"
    results = exporter.import_receipts(ROOT / case["path"], sink)
    assert results[-1]["status"] == case["journal"]
