"""Synthetic manual aggregate CLI; no wire expansion or real receiver."""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys

import pytest

import ext_contract as ext
from test_ext_contract import NOW, _auth, _records


@pytest.fixture(autouse=True)
def fixed_clock(monkeypatch):
    monkeypatch.setattr(ext.time, "time", lambda: NOW)


@pytest.fixture
def inputs(tmp_path):
    auth = _auth(tmp_path)
    records = tmp_path / "export.jsonl"
    records.write_text("".join(json.dumps(row) + "\n" for row in _records()))
    return {
        "auth": str(auth), "records": str(records),
        "state": str(tmp_path / "state"), "sink": str(tmp_path / "outbox")}


def _flags(inputs):
    return [value for key, value in inputs.items() for value in ("--" + key, value)]


def _cli(capsys, arguments):
    code = ext.main(arguments)
    return code, json.loads(capsys.readouterr().out)


def _tree(root):
    result = {}
    for path in [root, *sorted(root.rglob("*"))]:
        st = path.lstat()
        content = (os.readlink(path) if path.is_symlink() else
                   hashlib.sha256(path.read_bytes()).hexdigest() if path.is_file() else None)
        result[str(path.relative_to(root))] = (st.st_mode, st.st_mtime_ns, st.st_size, content)
    return result


def _accepted(inputs, eid):
    envelope = json.loads(
        (Path(inputs["sink"]) / "envelopes" / f"{eid}.json").read_text())
    counts = {}
    for record in envelope["records"]:
        counts[record["type"]] = counts.get(record["type"], 0) + 1
    return {"contract": ext.RECEIPT_CONTRACT, "kind": "receive", "status": "accepted",
            "envelope_id": eid, "records_sha256": envelope["records_sha256"],
            "records": envelope["record_count"], "accepted": counts, "acked_at": NOW}


@pytest.mark.parametrize("command", [[], ["deliver"]])
def test_legacy_and_named_delivery_preserve_numeric_hash_envelope_contract(
        inputs, capsys, command):
    code, result = _cli(capsys, [*command, *_flags(inputs)])
    assert code == 0 and result["status"] == "acked"
    envelope = json.loads(
        (Path(inputs["sink"]) / "envelopes" / f'{result["envelope_id"]}.json').read_text())
    expected = ext.build_envelope(
        _records(), ext.load_authorization(inputs["auth"]), NOW - 10)
    assert envelope == expected
    # Fixed /1 bytes hashed independently, not regenerated by this implementation.
    assert envelope["records_sha256"] == \
        "801489b384981cfdf055370dd4de7e6259593b68b4fa69253187885dd603c0f7"
    assert envelope["envelope_id"] == "a208a7570257f3011b4fba1d"
    assert ext._intent_hash(envelope) == \
        "f18599d8abc68d3acb4f11791089144762b4ab88940401527426fc626038a7a8"
    assert ext._canonical({"x": NOW, "small": 0.000001}) == \
        '{"small":1e-06,"x":1800000000.0}'
    assert "part" not in envelope
    assert set(ext.RECORD_TYPES) == {
        "meta", "coverage", "stat", "message", "attachment", "signal", "signals_truncated"}


@pytest.mark.parametrize("command", [["handoff"], ["deliver", "--sink-kind", "handoff"]])
def test_handoff_holds_without_self_ack_or_blind_resend(inputs, capsys, command):
    code, result = _cli(capsys, [*command, *_flags(inputs)])
    assert code == 0 and result["status"] == "held" and result["reason"] == "ack_unknown"
    sink = Path(inputs["sink"])
    assert not (sink / "acks").exists()
    assert sink.stat().st_mode & 0o777 == 0o700
    assert (sink / "envelopes").stat().st_mode & 0o777 == 0o700
    payload = sink / "envelopes" / f'{result["envelope_id"]}.json'
    before = (payload.read_bytes(), payload.stat().st_mtime_ns)
    code, again = _cli(capsys, [*command, *_flags(inputs)])
    assert code == 0 and again == result
    assert (payload.read_bytes(), payload.stat().st_mtime_ns) == before
    assert not (sink / "acks").exists()


@pytest.mark.parametrize("transport", ["json", "ndjson", "directory"])
def test_manual_receipt_import_reconciles_handoff_without_resend(
        inputs, capsys, tmp_path, transport):
    _, result = _cli(capsys, ["handoff", *_flags(inputs)])
    eid = result["envelope_id"]
    receipt = _accepted(inputs, eid)
    path = tmp_path / "receipts.json"
    path.write_text(json.dumps(receipt))
    if transport == "ndjson":
        path.write_text(json.dumps(receipt) + "\n" + json.dumps(receipt) + "\n")
    elif transport == "directory":
        directory = tmp_path / "receipts"
        directory.mkdir()
        path.rename(directory / "one.json")
        path = directory
    code, imported = _cli(capsys, [
        "reconcile", "--state", inputs["state"], "--sink", inputs["sink"],
        "--receipts", str(path)])
    assert code == 0
    assert {row["status"] for row in imported["results"]} == {"acked"}
    assert not (Path(inputs["sink"]) / "envelopes" / f"{eid}.json").exists()
    assert (Path(inputs["sink"]) / "acks" / f"{eid}.json").exists()
    _, again = _cli(capsys, ["handoff", *_flags(inputs)])
    assert again["status"] == "already_acked"


@pytest.mark.parametrize("selector", ["one", "all"])
def test_unacknowledged_reconcile_is_honestly_held(inputs, capsys, selector):
    _, result = _cli(capsys, ["handoff", *_flags(inputs)])
    code, report = _cli(capsys, [
        "reconcile", "--state", inputs["state"], "--sink", inputs["sink"],
        *(["--all"] if selector == "all" else ["--envelope-id", result["envelope_id"]])])
    assert code == 2
    rows = report["results"] if selector == "all" else [report]
    assert rows == [{"status": "held", "reason": "ack_unknown",
                     "envelope_id": result["envelope_id"]}]


def test_receiver_rejection_is_terminal_not_success(inputs, capsys, tmp_path):
    _, result = _cli(capsys, ["handoff", *_flags(inputs)])
    eid = result["envelope_id"]
    receipt = {"contract": ext.RECEIPT_CONTRACT, "kind": "receive", "status": "rejected",
               "envelope_id": eid, "reasons": ["record_field_not_exportable"],
               "rejected_at": NOW}
    path = tmp_path / "rejected.json"
    path.write_text(json.dumps(receipt))
    code, report = _cli(capsys, [
        "reconcile", "--state", inputs["state"], "--sink", inputs["sink"],
        "--receipts", str(path)])
    assert code == 1 and report["results"][0]["status"] == "rejected"
    code, retry = _cli(capsys, ["handoff", *_flags(inputs)])
    assert code == 1 and retry["status"] == "rejected"
    assert not (Path(inputs["sink"]) / "envelopes" / f"{eid}.json").exists()


@pytest.mark.parametrize("failure", ["malformed", "mismatch", "unknown_journal"])
def test_invalid_or_mismatched_receipts_never_ack(
        inputs, capsys, tmp_path, failure):
    _, result = _cli(capsys, ["handoff", *_flags(inputs)])
    receipt = _accepted(inputs, result["envelope_id"])
    if failure == "malformed":
        receipt["body"] = "SYNTH_BODY_SECRET"
    elif failure == "mismatch":
        receipt["records_sha256"] = "0" * 64
    else:
        receipt["envelope_id"] = "0" * 24
    path = tmp_path / "receipt.json"
    path.write_text(json.dumps(receipt))
    code, report = _cli(capsys, [
        "reconcile", "--state", inputs["state"], "--sink", inputs["sink"],
        "--receipts", str(path)])
    assert code == (2 if failure == "mismatch" else 1)
    assert "SYNTH_BODY_SECRET" not in json.dumps(report)
    assert not (Path(inputs["sink"]) / "acks").exists()
    assert ext.GovernedExporter(inputs["state"])._journal(result["envelope_id"])["status"] == "sent"


@pytest.mark.parametrize("sink_kind", ["local", "handoff"])
def test_withdraw_needs_delete_receipt_for_handoff_and_preserves_local_fake(
        inputs, capsys, tmp_path, sink_kind):
    _, result = _cli(capsys, ["deliver", "--sink-kind", sink_kind, *_flags(inputs)])
    eid = result["envelope_id"]
    code, withdrawn = _cli(capsys, [
        "withdraw", "--state", inputs["state"], "--sink", inputs["sink"],
        "--sink-kind", sink_kind, "--envelope-id", eid])
    if sink_kind == "local":
        assert code == 0 and withdrawn["status"] == "withdrawn"
    else:
        assert code == 2 and withdrawn["status"] == "delete_held"
        assert not (Path(inputs["sink"]) / "deletions").exists()
        receipt = tmp_path / "delete.json"
        receipt.write_text(json.dumps({
            "contract": ext.RECEIPT_CONTRACT, "kind": "delete",
            "envelope_id": eid, "deleted": True, "deleted_at": NOW}))
        code, reconciled = _cli(capsys, [
            "reconcile", "--state", inputs["state"], "--sink", inputs["sink"],
            "--receipts", str(receipt)])
        assert code == 0 and reconciled["results"][0]["status"] == "withdrawn"
    code, denied = _cli(capsys, ["deliver", "--sink-kind", sink_kind, *_flags(inputs)])
    assert code == 1 and denied["reason"] == "envelope_withdrawn"


@pytest.mark.parametrize("over,reason", [
    ({"scope": "detail"}, "auth_scope_not_aggregate"),
    ({"revoked": True}, "auth_revoked"),
    ({"expires_at": NOW}, "auth_expired"),
    ({"confirm_human": False}, "auth_not_human_confirmed"),
])
def test_manual_delivery_requires_existing_aggregate_human_authorization(
        inputs, capsys, over, reason):
    path = Path(inputs["auth"])
    auth = json.loads(path.read_text())
    path.write_text(json.dumps({**auth, **over}))
    code, report = _cli(capsys, ["handoff", *_flags(inputs)])
    assert code == 1 and report["reason"] == reason
    assert not Path(inputs["sink"]).exists()
    assert not Path(inputs["state"]).exists()


@pytest.mark.parametrize("change", ["body", "new_body_type", "mixed_generation"])
def test_cli_does_not_widen_record_allowlist_or_wire_contract(inputs, capsys, change):
    records = _records()
    if change == "body":
        records[-1]["body_text"] = "SYNTH_CLINICAL_SECRET"
    elif change == "new_body_type":
        records[-1]["type"] = "message_body"
    else:
        records[-1]["snapshot_generation_id"] = "different"
    Path(inputs["records"]).write_text("".join(json.dumps(row) + "\n" for row in records))
    code, report = _cli(capsys, ["handoff", *_flags(inputs)])
    assert code == 1 and report["status"] == "refused"
    assert "SYNTH_CLINICAL_SECRET" not in json.dumps(report)
    assert not Path(inputs["sink"]).exists()


def test_health_counts_and_authorization_are_readonly_and_redacted(
        inputs, capsys, tmp_path, monkeypatch):
    _, result = _cli(capsys, ["handoff", *_flags(inputs)])
    journal = Path(inputs["state"]) / "journal"
    for number, status in enumerate(
            ("held", "delete_held", "acked", "withdrawn", "refused", "rejected"), 1):
        eid = f"{number:024x}"
        (journal / f"{eid}.json").write_text(json.dumps({
            "envelope_id": eid, "status": status,
            "attempts": [{"ts": NOW - 30, "status": status}],
            "actor": "SYNTH_ACTOR_SECRET", "body": "SYNTH_BODY_SECRET",
            "reason": "SYNTH_REASON_SECRET", "sink_root": inputs["sink"]}))
    (journal / ("f" * 24 + ".json")).write_text("{corrupt")
    payload = Path(inputs["sink"]) / "envelopes" / f'{result["envelope_id"]}.json'
    payload.unlink()
    before = _tree(tmp_path)

    def forbidden(*args, **kwargs):
        pytest.fail("health invoked a writer or sink action")

    monkeypatch.setattr(ext, "GovernedExporter", forbidden)
    monkeypatch.setattr(ext, "HandoffSink", forbidden)
    monkeypatch.setattr(ext, "_write_json", forbidden)
    code, report = _cli(capsys, [
        "health", "--state", inputs["state"], "--auth", inputs["auth"],
        "--sink", inputs["sink"]])
    assert code == 2 and report["status"] == "unknown"
    assert report["counts"] == {
        "held": 2, "delete_held": 1, "acked": 1, "withdrawn": 1,
        "refused": 1, "rejected": 1, "corrupt": 1}
    assert report["oldest_held_age_s"] == 30
    assert report["authorization"] == {"state": "valid", "seconds_left": 3600}
    assert "payload_missing" in report["reasons"]
    assert report["complete"] is False
    output = json.dumps(report)
    assert "SECRET" not in output and str(tmp_path) not in output
    assert result["envelope_id"] not in output
    assert _tree(tmp_path) == before


@pytest.mark.parametrize("case", ["missing", "oversized", "symlink", "fifo",
                                "entry_limit", "invalid_auth", "expired_auth",
                                "revoked_auth", "invalid_budget"])
def test_health_negative_inputs_are_bounded_redacted_and_unchanged(
        inputs, capsys, tmp_path, case):
    _, result = _cli(capsys, ["handoff", *_flags(inputs)])
    journal = Path(inputs["state"]) / "journal" / f'{result["envelope_id"]}.json'
    extra = []
    if case == "missing":
        inputs["state"] = str(tmp_path / "absent")
    elif case == "oversized":
        journal.write_bytes(b" " * (ext.RECEIPT_MAX_BYTES + 1))
    elif case == "symlink":
        journal.unlink()
        journal.symlink_to(inputs["auth"])
    elif case == "fifo":
        journal.unlink()
        os.mkfifo(journal)
    elif case == "entry_limit":
        (journal.parent / ("f" * 24 + ".json")).write_text("{}")
        extra = ["--max-entries", "1"]
    elif case == "invalid_auth":
        Path(inputs["auth"]).write_text(json.dumps({"SYNTH_AUTH_SECRET": "SYNTH_SECRET"}))
    elif case in ("expired_auth", "revoked_auth"):
        path = Path(inputs["auth"])
        auth = json.loads(path.read_text())
        auth.update({"expires_at": NOW - 1} if case == "expired_auth" else {"revoked": True})
        path.write_text(json.dumps(auth))
    else:
        extra = ["--max-entries", "0"]
    before = _tree(tmp_path)
    code, report = _cli(capsys, [
        "health", "--state", inputs["state"], "--auth", inputs["auth"], *extra])
    assert code in (1, 2)
    assert report["status"] in ("unknown", "refused")
    assert "SYNTH" not in json.dumps(report) and str(tmp_path) not in json.dumps(report)
    assert _tree(tmp_path) == before
    if case == "entry_limit":
        assert report["complete"] is False and "journal_entry_limit" in report["reasons"]


@pytest.mark.parametrize("action", ["legacy", "handoff", "health"])
def test_direct_script_entry_preserves_old_invocation_and_local_commands(
        inputs, tmp_path, action):
    repo = Path(__file__).resolve().parents[2]
    # Load the existing sandbox guards before running the actual script.
    code = ("import runpy,sys,time;runpy.run_path(sys.argv.pop(1));"
            "time.time=lambda:1800000000.0;"
            "runpy.run_path(sys.argv.pop(1),run_name='__main__')")
    if action == "health":
        arguments = ["health", "--state", inputs["state"], "--auth", inputs["auth"]]
    else:
        arguments = ([] if action == "legacy" else ["handoff"]) + _flags(inputs)
    before = _tree(tmp_path) if action == "health" else None
    result = subprocess.run(
        [sys.executable, "-c", code, str(repo / "tests/conftest.py"),
         str(repo / "mcs/ops/ext_contract.py"), *arguments],
        capture_output=True, text=True, timeout=10, check=False)
    report = json.loads(result.stdout)
    assert result.returncode == (2 if action == "health" else 0), result.stderr
    assert report["status"] == {"legacy": "acked", "handoff": "held", "health": "unknown"}[action]
    if before is not None:
        assert _tree(tmp_path) == before


def test_real_synthetic_database_export_handoff_round_trip(tmp_path, capsys):
    import brain_export
    import ledger
    from semantic_testkit import _ledger, _message, _patient

    db = _ledger(tmp_path)
    _patient(db)
    db.save_messages([_message(1, body="SYNTHETIC_BODY_NEVER_ON_WIRE")], project_id=1)
    db.close()
    snapshot = ledger.publish_snapshot(str(tmp_path / "ledger.db"), str(tmp_path / "snapshots"))
    brain_export.run(tmp_path / "export", Path(snapshot))
    inputs = {"auth": str(_auth(tmp_path, fields=list(ext.RECORD_TYPES))),
              "records": str(tmp_path / "export/export.jsonl"),
              "state": str(tmp_path / "state"), "sink": str(tmp_path / "outbox")}
    _, result = _cli(capsys, ["handoff", *_flags(inputs)])
    eid = result["envelope_id"]
    payload = Path(inputs["sink"]) / "envelopes" / f"{eid}.json"
    assert "SYNTHETIC_BODY_NEVER_ON_WIRE" not in payload.read_text()
    receipt = tmp_path / "receipt.ndjson"
    receipt.write_text(json.dumps(_accepted(inputs, eid)) + "\n")
    code, reconciled = _cli(capsys, [
        "reconcile", "--state", inputs["state"], "--sink", inputs["sink"],
        "--receipts", str(receipt)])
    assert code == 0 and reconciled["results"][0]["status"] == "acked"
    assert not payload.exists()


def test_legacy_unresolved_delivery_keeps_exit_one_without_resend(inputs, capsys):
    _, held = _cli(capsys, ["handoff", *_flags(inputs)])
    code, legacy = _cli(capsys, _flags(inputs))
    assert code == 1 and legacy == held
    assert not (Path(inputs["sink"]) / "acks").exists()


def test_handoff_cannot_select_a_self_acknowledging_local_consumer(inputs, tmp_path):
    before = _tree(tmp_path)
    with pytest.raises(SystemExit) as exc:
        ext.main(["handoff", "--sink-kind", "local", *_flags(inputs)])
    assert exc.value.code == 2
    assert _tree(tmp_path) == before


def test_health_success_reports_terminal_counts_without_any_write(inputs, capsys, tmp_path):
    _cli(capsys, _flags(inputs))
    before = _tree(tmp_path)
    code, report = _cli(capsys, [
        "health", "--state", inputs["state"], "--auth", inputs["auth"],
        "--sink", inputs["sink"]])
    assert code == 0 and report["status"] == "ok" and report["complete"] is True
    assert report["counts"]["acked"] == 1
    assert sum(report["counts"].values()) == 1
    assert report["reasons"] == []
    assert _tree(tmp_path) == before
